config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'heyen' && password == 'zxy123456'
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  root 'home#index'

  resources :products do
    member do
      get :show_version
      get :upload_file
      patch :do_upload_file
      get :edit_file
      patch :update_file
      get :apply
      patch :do_apply
    end
    collection do
      post :do_develop_audit
      post :do_flow_audit
      post :do_active_audit
      post :do_failed_audit
      get :import
      post :do_import
    end
  end

  resources :instances do
    member do
      get :show_version
      get :upload_file
      patch :do_upload_file
      get :edit_file
      patch :update_file
      get :apply
      patch :do_apply
    end
    collection do
      post :do_develop_audit
      post :do_flow_audit
      post :do_active_audit
      post :do_failed_audit
      get :import
      post :do_import
    end
  end

  resources :audits do
    collection do
      get :products
      get :instances
      get :technologies
    end
  end
  resources :technologies do
    member do
      get :show_version
      get :upload_file
      patch :do_upload_file
      get :edit_file
      patch :update_file
      get :apply
      patch :do_apply
    end
    collection do
      post :do_develop_audit
      post :do_flow_audit
      post :do_active_audit
      post :do_failed_audit
    end
  end
  resources :notices do
    collection do
      get :receives
      get :sends
    end
    member do
      get :show_notice
      get :reply
      patch :do_reply
      patch :read
    end
  end
  resources :home, only: [:index] do
    collection do
      get :cytoscape
      get :files_search
      get :stl
    end
  end

  resources :matters do
    member do
      get :upload_file
      patch :do_upload_file
      get :notices
      patch :send_notice
      patch :countersign
      patch :agree
    end
  end
end

app/models/instance.rb
class Instance < ActiveRecord::Base
  include FileConcern
  has_paper_trail versions: {
      scope: -> { order("id desc") }
  }
  has_ancestry

  belongs_to :user
  belongs_to :last_user, foreign_key: :last_user_id, class_name: 'User'
  belongs_to :file_user, foreign_key: :file_user_id, class_name: 'User'
  belongs_to :instance_category
  belongs_to :technology

  has_many :instance_logs
  has_many :products_instances, dependent: :destroy
  has_many :technology_instances, dependent: :destroy
  has_many :notices, -> {where(model_type: 'Instance')}, class_name: 'Notice', foreign_key: :model_id

  has_and_belongs_to_many :products, join_table: 'products_instances'
  has_and_belongs_to_many :users, join_table: 'instances_users'
  has_and_belongs_to_many :organizations, join_table: 'instance_organizations'
  has_and_belongs_to_many :technologies, join_table: 'technology_instances'

  validates_presence_of :name, :instance_no
  validates_uniqueness_of :name, :instance_no

  # after_save :do_stp2_stl


  def view_logs user
    if user.has_instance_log_resource?
      self.instance_logs
    else
      self.instance_logs.where(user: user)
    end
  end

  def get_model_name
    '零件'
  end

  # def technology
  #   technologies.order('valid_at desc, updated_at desc').first
  # end

  class << self
    def search_conn params
      instances = Instance.joins(:user).all
      if params[:table_search].present?
        instances = instances.where('instances.instance_no like ? or instances.name like ? or instances.norms like ? or users.name like ?',
                                  "%#{params[:table_search]}%", "%#{params[:table_search]}%", "%#{params[:table_search]}%",
                                  "%#{params[:table_search]}%")
      end
      instances
    end

    def get_model_name
      '零件'
    end
  end
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_action :set_instance, only: [:show, :edit, :update, :destroy, :show_version, :upload_file, :do_upload_file]
  before_action :set_uptoken, only: [:upload_file, :edit_file]
  before_action :set_log, only: [:edit_file, :update_file, :apply, :do_apply]
  before_action :set_audit_log, only: [:do_develop_audit, :do_flow_audit, :do_active_audit, :do_failed_audit]
  include ApplicationHelper
  def index
    @instances = Instance.search_conn(params).order('updated_at desc').page(params[:page]).per(Settings.per_page)
  end

  def new
    @instance = Instance.new
    render layout: false
  end

  def create
    @instance = Instance.new
    @instance.user = current_user
    @flag = @instance.update instance_permit
  end

  def show

  end

  def edit
    render layout: false
  end

  def update
    @flag = @instance.update instance_permit
  end

  def destroy
    if @instance.destroy
      redirect_to instances_path, notice: '删除成功'
    else
      redirect_to instances_path, alert: '删除失败'
    end
  end

  def upload_file
    render layout: false
  end

  def do_upload_file
    @log = InstanceLog.new instance: @instance, file_path: params[:path], file_name: params[:file_name], user: current_user
    @log.save validate: false
    render js: 'location.reload()'
  end

  def show_version
    @version = @instance.versions.find_by id: params[:version_id]
    render layout: false
  end

  def apply
    render layout: false
  end

  def do_apply
    @instance = @log.instance
    begin
      if @log.update log_permit
        @log.do_apply!
        @flag = true
      else
        @flag = false
      end
    rescue => e
      @flag = false
    end
  end

  def edit_file
    render layout: false
  end

  def update_file
    @instance = @log.instance
    # @flag = @log.update_columns file_path: params[:path], file_name: params[:file_name]
    @log.attributes = {file_path: params[:path], file_name: params[:file_name]}
    @flag = @log.save validate: false
  end

  def do_develop_audit
    begin
      from_status = @log.status
      @log.do_develop_audit!
      @log.audits.create from_status: from_status, to_status: @log.status, user: current_user
      @flag = true
    rescue => e
      @flag = false
    end
    render js: 'location.reload()'
  end

  def do_flow_audit
    begin
      from_status = @log.status
      @log.do_flow_audit!
      @log.audits.create from_status: from_status, to_status: @log.status, user: current_user
      @flag = true
    rescue => e
      @flag = false
    end
    render js: 'location.reload()'
  end

  def do_active_audit
    begin
      from_status = @log.status
      @log.do_active_audit!
      @log.audits.create from_status: from_status, to_status: @log.status, user: current_user
      @flag = true
    rescue => e
      @flag = false
    end
    render js: 'location.reload()'
  end

  def do_failed_audit
    begin
      from_status = @log.status
      @log.do_failed_audit!
      @log.audits.create from_status: from_status, to_status: @log.status, user: current_user
      @flag = true
    rescue => e
      @flag = false
    end
    render js: 'location.reload()'
  end

  def import
    render layout: false
  end

  def do_import
    begin
      Import::InstanceImporter.import(params[:file].path, params: {user: current_user}) if params[:file]
      redirect_to instances_path, notice: '导入成功！'
    rescue => e
      redirect_to instances_path, alert: e.message
    end
  end

  private

  def instance_permit
    params.require('instance').permit(:instance_no, :name, :norms, :parent_id,  :desc, :instance_category_id, :technology_id, user_ids: [], product_ids: [], organization_ids: [])
  end

  def log_permit
    params.require('instance_log').permit(:develop_id, :flow_id, :active_id)
  end

  def set_instance
    @instance = Instance.find_by id: params[:id]
    redirect_to instances_path, alert: '找不到数据' unless @instance.present?
  end

  def set_log
    @log = current_user.instance_logs.find_by id: params[:id]
    redirect_to instances_path, alert: '找不到数据' unless @log.present?
  end

  def set_audit_log
    @log = InstanceLog.find_by id: params[:id]
    redirect_to instances_path, alert: '找不到数据' unless @log.present?
  end

  def set_uptoken
    @uptoken = uptoken
  end
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/_apply_form.html.erb
<div id="form">
  <div class="modal-header" style="padding:5px; padding-left: 15px;">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="file-modal-label"></h4>
  </div>
  <%= simple_form_for(@log, url: do_apply_instance_path(@log), html: {class: 'form-horizontal group_form', onkeydown: "if(event.keyCode==13)return false;"}, wrapper: :horizontal_form) do |f| %>
    <div class="modal-body" >
      <%= f.input :develop_id, collection: current_user.audit_users(:develop, :instances).all.collect{|user| [user.name, user.id]}, input_html: { class: 'select2', width: '100%', style: 'width: 100%'} %>
      <%= f.input :flow_id, collection: current_user.audit_users(:flow, :instances).all.collect{|user| [user.name, user.id]} , input_html: { class: 'select2', width: '100%', style: 'width: 100%'}%>
      <%= f.input :active_id, collection: current_user.audit_users(:active, :instances).all.collect{|user| [user.name, user.id]} , input_html: { class: 'select2', width: '100%', style: 'width: 100%'}%>
    </div>
  <% end %>

  <div class="modal-footer">
    <%= button_tag '保存', class: 'btn btn-primary commit commit', data: { disable_with: '保存中' } %>
    <button type="button" class="btn btn-default" data-dismiss="modal">返回</button>
  </div>
</div>
<script tye="text/javascript">
    //ajax提交表单
    $(function(){
        $('.commit').click(function(){
            showSpinner();
            $.ajax({
                type: "Patch",
                url: $('.group_form').attr('action'),
                data: $('.group_form').serialize(),
                dataType: 'script',
                async: false,
                error: function(request) {
                    alert("Connection error");
                },
                success: function(data) {
                    //接收后台返回的结果
                }
            });

        });
        $('.select2').select2();
    });
</script>

app/views/instances/_detail.html.erb
<div class="row">
  <div class="table-responsive col-sm-6">
    <table class="table">
      <tbody>
      <tr>
        <th style="width:50%">零件编号</th>
        <td><%= @instance.instance_no %></td>
      </tr>
      <tr>
        <th>零件名</th>
        <td><%= @instance.name %></td>
      </tr>
      <tr>
        <th>父节点</th>
        <td><%= @instance.parent&.name %></td>
      </tr>
      <tr>
        <th>物料属性</th>
        <td><%= @instance.instance_category&.name %></td>
      </tr>
      <tr>
        <th>型号</th>
        <td><%= @instance.norms %></td>
      </tr>

      <tr>
        <th>
          图纸
        </th>
        <td>
          <% if @instance.file_path.present? && current_user.can_view?(@instance)%>
            <a href="javascript:void(0)" onclick="show_file(this)" class="btn show-file" data-url="<%= @instance.preview_url%>" data-file-name="<%= @instance.file_name %>">
              <i class="fa fa-eye"></i><%= show_file_name '文件',  @instance %>
            </a>
            <%= link_to @instance.download_url, class: 'btn' do  %>
              <i class="fa fa-download"></i>
            <% end %>
          <% else %>
            <%= @instance.file_name %>
          <% end %>
        </td>
      </tr>

      <tr>
        <th>图纸可见部门</th>
        <td>
          <% @instance.organizations.each do |org| %>
            <span class="label label-primary " style="padding-bottom: 2px;padding-top: 2px;"><%= org.name %></span>
          <% end %>
        </td>
      </tr>


      </tbody>
    </table>
  </div>
  <div class="table-responsive col-sm-6">
    <table class="table">
      <tbody>
      <tr>
        <th>创建人</th>
        <td><%= @instance&.user&.name %></td>
      </tr>
      <tr>
        <th>创建时间</th>
        <td><%= simple_time @instance.created_at %></td>
      </tr>
      <tr>
        <th>图纸变更人</th>
        <td><%= @instance&.file_user&.name %></td>
      </tr>
      <tr>
        <th>图纸变更时间</th>
        <td><%= simple_time @instance.last_updated_at %></td>
      </tr>
      <% if can? :cytoscape, :home %>
<!--      <tr>-->
<!--        <th>-->
<!--          关系图-->
<!--        </th>-->
<!--        <td>-->
            <%#= link_to cytoscape_home_index_path(instance_id: @instance.id),  class: 'btn btn-primary btn-xs', target: "view_window" do %>
<!--              <i class="fa fa-gg"></i>关系图-->
            <%# end %>
<!--        </td>-->
<!--      </tr>-->
      <% end %>
      <tr>
        <th>备注</th>
        <td><%= @instance.desc %></td>
      </tr>
      <tr>
        <th>工艺文件</th>
        <td><%= link_to @instance.technology&.name, technology_path(@instance.technology) if @instance.technology.present? %></td>
      </tr>
      <tr>
        <th>图纸可见人员</th>
        <td>
          <% @instance.users.each do |user| %>
            <span class="label label-primary " style="padding-bottom: 2px;padding-top: 2px;"><%= user.name %></span>
          <% end %>
        </td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/instances/_instance_logs.html.erb
<div class="row" id="instance_logs">
  <div class="col-md-12">
    <div class="box">

      <!-- /.box-header -->
      <div class="box-body">
        <table class="table table-bordered">
          <tr>
            <th>文件名</th>
            <th>上传人</th>
            <th>上传时间</th>
            <th>状态</th>
            <th>生效时间</th>
            <th></th>
          </tr>
          <tr>
            <% if @instance.view_logs(current_user).order('instance_logs.updated_at desc').present? %>
              <% @instance.view_logs(current_user).order('instance_logs.updated_at desc').each do |instance_log| %>
                <tr>
                  <td>
                    <% if instance_log.file_path.present? %>
                      <a href="javascript:void(0)" onclick="show_file(this)" class="btn show-file" data-url="<%= instance_log.preview_url%>" data-file-name="<%= instance_log.file_name %>">
                        <i class="fa fa-eye"></i><%= show_file_name '文件',  instance_log %>
                      </a>
                      <%= link_to instance_log.download_url, class: 'btn' do  %>
                        <i class="fa fa-download"></i>
                      <% end %>
                      <% else %>
                      <%= instance_log.file_name %>
                    <% end %>
                  </td>
                  <td><%= instance_log.user&.name %></td>
                  <td><%= simple_time_mini instance_log.updated_at %></td>
                  <td><%= instance_log.get_status %></td>
                  <td><%= simple_time_mini instance_log.active_at %></td>
                  <td>
                    <% if can? :apply, :instances %>
                    <% if instance_log.may_do_apply? && @current_user == instance_log.user  %>
                        <%= link_to '申请', apply_instance_path(instance_log) , class: 'font-a label bg-green', 'data-toggle' => "modal", 'data-target' => "#global-modal" %>
                    <% end %>
                    <% end %>

                    <% if can? :edit_file, :instances %>
                      <% if ['wait', 'failed'].include? instance_log.status %>
                        <%= link_to '图纸变更', edit_file_instance_path(instance_log), 'data-toggle' => "modal", 'data-target' => "#global-modal", class: 'btn btn-primary btn-xs'%>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="5" align="center">没有可显示的内容</td>
            </tr>
          <% end %>
          </tr>
        </table>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/instances/_list.html.erb
<div class="row" id="instance-list">
  <div class="col-md-12">
    <div class="box">
      <%= form_tag instances_path, method: :get do%>
      <div class="box-header with-border">
        <h3 class="box-title">零件列表</h3>
        <% if can? :new, :instances %>
          <small><%= link_to '添加零件', new_instance_path , class: 'font-a label bg-green', 'data-toggle' => "modal", 'data-target' => "#global-modal" %></small>
        <% end %>
        <% if can? :import, :instances %>
          <small><%= link_to 'Bom单导入', import_instances_path, 'data-toggle' => "modal", 'data-target' => "#global-modal", class: 'font-a label bg-primary' %></small>
        <% end %>
      </div>
      <div class="box-tools">
        <div class="input-group input-group-sm">
          <div class="pull-right">
            <div class="col-xs-12">
              <input type="text" name="table_search" class="form-control" placeholder="检索" value="<%= params[:table_search] %>">
            </div>
          </div>

          <div class="input-group-btn">
            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
          </div>
        </div>
      </div>


      <% end %>
      <!-- /.box-header -->
      <div class="box-body">

        <table id="demo" class="table table-bordered"></table>
      </div>
      <script type="text/javascript">
          var treeTable = $('#demo').bootstrapTreeTable({
              expandAll : false,                // 是否全部展开
              expandFirst : false,
              toolbar: null,//顶部工具条
              columns: [{
                  title: '编号',
                  field: 'no',
                  width: '20%',
                  formatter: function (value, row, index) {
                     return "<a href='/instances/" + row.model_id +  "'> " + row.no + "</a>"
                  }
              },{
                  title: '名称',
                  field: 'name',
                  width: '20%'
              },{
                  title: '类型',
                  field: 'model_type',
                  width: '10%'
              },{
                  title: '型号',
                  field: 'norms',
                  width: '20%'
              },{
                  title: '创建人',
                  field: 'user_name',
                  width: '10%'
              },{
                  title: '操作',
                  field: 'action',
                  width: '20%',
                  formatter: function(value,row, index) {
                      var actions = [];
                      <% if can? :edit, :instances %>
                      actions.push('<a class="btn btn-success btn-xs" data-toggle="modal" data-target="#global-modal" href="/instances/' + row.model_id + '/edit"> <i class="fa fa-edit"></i>编辑 </a>');
                      <% end %>
                      <% if can? :destroy, :instances %>
                      actions.push('<a data-confirm="确定删除吗？" style="margin-left:5px;"  class="btn btn-danger btn-xs" rel="nofollow" data-method="delete" href="/instances/' + row.model_id + '"> <i class="fa fa-close"></i>删除 </a>');
                      <% end %>
                      return actions.join('');
                  }
              }],
              data: JSON.parse('<%= raw instances_tree instances, 0 %>')
          });
          $('.treetable-bars').hide();
      </script>
      <!-- /.box-body -->
      <div class="box-footer clearfix">
        <div class="pull-right pagination-sm no-margin">
          <%= paginate instances, params: {table_search: params[:table_search]} %>
        </div>
      </div>
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/instances/_versions.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="box">

      <!-- /.box-header -->
      <div class="box-body">
        <table class="table table-bordered">
          <tr>
            <th>零件编号</th>
            <th>零件名</th>
            <th>型号</th>
            <th>被变更时间</th>
            <th>图纸创建人</th>
            <th>图纸</th>
          </tr>
          <tr>
            <% if @instance.versions.present? %>
              <% @instance.versions.each do |version| %>
              <% if version.reify.present? %>
                <tr>
                  <td><%= link_to version.reify.instance_no, show_version_instance_path(version.reify, version_id: version.id), 'data-toggle' => "modal", 'data-target' => "#global-modal" %></td>
                  <td><%= version.reify.name %></td>
                  <td><%= version.reify.norms %></td>
                  <td><%= simple_time_mini version.created_at %></td>
                  <td><%= version.reify&.file_user&.name %></td>
                  <td>
                    <% if version.reify.file_path.present?  %>
                      <% if current_user.can_view?(@instance) %>
                        <a href="javascript:void(0)" onclick="show_file(this)" class="btn show-file" data-url="<%= version.reify.preview_url%>" data-file-name="<%= version.reify.file_name %>">
                          <i class="fa fa-eye"></i><%= show_file_name '文件',  version.reify %>
                        </a>
                        <%= link_to version.reify.download_url, class: 'btn' do  %>
                          <i class="fa fa-download"></i>
                        <% end %>
                      <% else %>
                        <%= show_file_name '文件',  version.reify %>
                      <% end %>

                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          <% else %>
            <tr>
              <td colspan="5" align="center">没有可显示的内容</td>
            </tr>
          <% end %>
          </tr>
        </table>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/instances/apply.html.erb
<%= render 'apply_form' %>

app/views/instances/create.js.erb
<% if @flag %>
  $('#global-modal').modal('hide');
show_flash('success', '创建成功')
  location.reload();
<% else %>
hideSpinner();
  $('#form').html('<%= j render "/instances/form"%>');
<% end %>

app/views/instances/do_apply.js.erb
<% if @flag %>
show_flash('success', '申请成功');
location.reload()
<% else %>
$('#form').replaceWith('<%= j render(partial: 'instances/apply_form') %>');
<% end %>
hideSpinner();

app/views/instances/edit.html.erb
<%= render 'instances/form' %>

app/views/instances/import.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="myModalLabel">Bom单-批量导入</h4>
</div>
<%= form_tag(do_import_instances_path, multipart: true) do %>
  <div class="modal-body">
    <ol>
      <table class="table table-condensed table-bordered">
        <thead>
        <th>层级</th>
        <th>物料代码</th>
        <th>物料名称</th>
        <th>规格型号</th>
        <th>物料属性</th>
        </thead>
        <tbody>
        <td>必填</td>
        <td>必填</td>
        <td>必填</td>
        <td>选填</td>
        <td>选填</td>
        </tbody>
      </table>

      <ul>
        <li>表格样式如上所示,表头（第一行）必须和上述表格一致</li>
        <li>【物料属性】必须提前录入到系统当中</li>
        <li>【物料代码】为物料的唯一标识，如果重复导入会更新物料信息</li>
      </ul>
    </ol>

    <p style="padding:50px"><%= file_field_tag :file, accept: 'application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' %></p>
  </div>

  <div class="modal-footer">
    <%= submit_tag '保存', class: 'btn btn-primary', data: { disable_with: "处理中..." } %>
    <button type="button" class="btn btn-default" data-dismiss="modal">返回</button>
  </div>
<% end %>

app/views/instances/index.html.erb
<%= render 'instances/header' %>

<%= render partial: 'instances/list', locals: {instances: @instances} %>

app/views/instances/new.html.erb
<%= render 'instances/form' %>

app/views/instances/show_version.html.erb
<div class="modal-header" style="padding:5px; padding-left: 15px;">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h4 class="modal-title" id="file-modal-label"></h4>
</div>

<div class="modal-body" >
  <table class="table">
    <tbody>

    <tr>
      <th style="width:50%">零件编号</th>
      <td><%= @version.reify&.instance_no %></td>
    </tr>
    <tr>
      <th>零件名</th>
      <td><%= @version.reify&.name %></td>
    </tr>
    <tr>
      <th>型号</th>
      <td><%= @version.reify&.norms %></td>
    </tr>
    <tr>
      <th>创建人</th>
      <td><%= @version.reify&.user&.name %></td>
    </tr>
    <tr>
      <th>被变更时间</th>
      <td><%= simple_time @version.created_at %></td>
    </tr>
    <tr>
      <th>图纸变更人</th>
      <td><%= @version.reify&.file_user&.name %></td>
    </tr>
    <tr>
      <th>图纸生效时间</th>
      <td><%= simple_time @version.reify&.active_at %></td>
    </tr>
    <tr>
      <th>备注</th>
      <td><%= @version.reify&.desc %></td>
    </tr>
    </tbody>
  </table>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">返回</button>
</div>

app/views/instances/update.js.erb
<% if @flag %>
$('#global-modal').modal('hide');
show_flash('success', '修改成功')
location.reload();
<% else %>
hideSpinner();
$('#form').html('<%= j render "/instances/form"%>');
<% end %>