config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'heyen' && password == 'zxy123456'
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  root 'home#index'

  resources :products do
    member do
      get :show_version
      get :upload_file
      patch :do_upload_file
      get :edit_file
      patch :update_file
      get :apply
      patch :do_apply
    end
    collection do
      post :do_develop_audit
      post :do_flow_audit
      post :do_active_audit
      post :do_failed_audit
      get :import
      post :do_import
    end
  end

  resources :instances do
    member do
      get :show_version
      get :upload_file
      patch :do_upload_file
      get :edit_file
      patch :update_file
      get :apply
      patch :do_apply
    end
    collection do
      post :do_develop_audit
      post :do_flow_audit
      post :do_active_audit
      post :do_failed_audit
      get :import
      post :do_import
    end
  end

  resources :audits do
    collection do
      get :products
      get :instances
      get :technologies
    end
  end
  resources :technologies do
    member do
      get :show_version
      get :upload_file
      patch :do_upload_file
      get :edit_file
      patch :update_file
      get :apply
      patch :do_apply
    end
    collection do
      post :do_develop_audit
      post :do_flow_audit
      post :do_active_audit
      post :do_failed_audit
    end
  end
  resources :notices do
    collection do
      get :receives
      get :sends
    end
    member do
      get :show_notice
      get :reply
      patch :do_reply
      patch :read
    end
  end
  resources :home, only: [:index] do
    collection do
      get :cytoscape
      get :files_search
      get :stl
    end
  end

  resources :matters do
    member do
      get :upload_file
      patch :do_upload_file
      get :notices
      patch :send_notice
      patch :countersign
      patch :agree
    end
  end
end

app/models/matter.rb
class Matter < ActiveRecord::Base
  include FileConcern
  has_paper_trail only: [:file_path, :file_name], versions: {
      scope: -> { order("id desc") }
  }
  STATUS = {circulation: '流转中', countersign: '会签中', active: '已完成'}
  has_many :notices, -> {where(model_type: 'Matter')}, class_name: 'Notice', foreign_key: :model_id
  belongs_to :user
  belongs_to :file_user, foreign_key: :file_user_id, class_name: 'User'
  belongs_to :countersign_user, foreign_key: :countersign_user_id, class_name: 'User'
  validates_presence_of :name
  has_and_belongs_to_many :users, join_table: 'user_matters'
  has_many :user_matters
  

  def user_matter user
    self.user_matters.where(user: user).first
  end

  def get_status
    Matter::STATUS[self.status.to_sym]
  end

  def check_agree
    flag = true
    self.user_matters.each do |user_matter|
      flag = flag & user_matter.agree
    end
    self.update agree: true, status: :active if flag
  end



  class << self
    def search_conn params
      matters = Matter.joins(:user).all
      if params[:table_search].present?
        matters = matters.where('matters.name like ? or users.name like ?',
                                  "%#{params[:table_search]}%", "%#{params[:table_search]}%")
      end
      matters
    end

    def get_model_name
      'Bom单'
    end
  end
end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
  include ApplicationHelper
  before_action :set_matter, only: [:show, :edit, :update, :destroy, :upload_file, :do_upload_file, :notices, :send_notice, :countersign, :agree]
  before_action :set_uptoken, only: [:upload_file]
  def index
    @matters = Matter.search_conn(params).order('updated_at desc').page(params[:page]).per(Settings.per_page)
  end

  def new
    @matter = current_user.matters.new
    render layout: false
  end

  def create
    @matter = current_user.matters.new
    @flag = @matter.update matter_permit
  end

  def show

  end

  def edit
    render layout: false
  end

  def update
    @flag = @matter.update matter_permit
  end

  def destroy
    if @matter.destroy
      redirect_to matters_path, notice: '删除成功'
    else
      redirect_to matters_path, alert: '删除失败'
    end
  end

  def upload_file
    render layout: false
  end

  def do_upload_file
    user_matter = UserMatter.find_by user: current_user, matter: @matter
    UserMatter.create user: current_user, matter: @matter unless user_matter.present?
    @matter.update file_path: params[:path], file_name: params[:file_name], file_user: current_user, last_update_at: DateTime.now
    render js: 'location.reload()'
  end

  def show_version
    @version = @matter.versions.find_by id: params[:version_id]
    render layout: false
  end

  def notices
    #render layout: false
    render layout: false
  end

  def send_notice
    if params[:user_ids].present?
      params[:user_ids].each do|user_id|
        user = User.find_by id: user_id
        current_user.send_bom_notice user, @matter if user.present?
      end
    end
  end

  def agree
    user_matter = @matter.user_matter current_user

    user_matter.update agree: true
  end

  def countersign
    @matter.update countersign_user: current_user, countersign_at: DateTime.now, status: 'countersign'
    current_user.send_countersign_notice @matter.users, @matter
  end

  private
  def matter_permit
    params.require('matter').permit(:name, :desc)
  end

  def set_matter
    @matter = Matter.find_by id: params[:id]
    redirect_to matters_path, alert: '找不到数据' unless @matter.present?
  end

  def set_uptoken
    @uptoken = uptoken
  end
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/views/matters/_countersign.html.erb
<div class="row">
  <div class="table-responsive col-sm-10">
    <div class="box-body">
      <table class="table table-bordered">
        <tr>
          <th>会签人员</th>
          <th>会签时间</th>
          <th>状态</th>
          <th></th>
        </tr>
        <% @matter.user_matters.each do |user_matter| %>
          <tr>
            <td><%= user_matter.user&.name %></td>
            <td><%= simple_time_mini user_matter.updated_at %></td>
            <td><%= user_matter.format_agree %></td>
            <td>
              <% if current_user == user_matter.user && user_matter.format_agree == '待确认' %>
                <%= button_tag '会签', class: 'btn btn-success commit', id: 'agree' if can? :countersign, :matters %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <script type="text/javascript">
      $(function(){
          $('#agree').click(function(){
              if(confirm('确认同意会签吗？')){
                  showSpinner();
                  $.ajax({
                      type: "PATCH",
                      url: '<%= agree_matter_path @matter %>',
                      dataType: 'script',
                      async: false,
                      error: function(request) {
                          alert("Connection error");
                      },
                      success: function(data) {
                          //接收后台返回的结果
                      }
                  });
              }
          });
      });
  </script>
</div>

app/views/matters/_detail.html.erb
<div class="row">
  <div class="table-responsive col-sm-6">
    <table class="table">
      <tbody>
      <tr>
        <th style="width:50%">名称</th>
        <td><%= @matter.name %></td>
      </tr>
      <tr>
        <th style="width:50%">创建人</th>
        <td><%= @matter.user&.name %></td>
      </tr>

      <tr>
        <th style="width:50%">文件最后变更人</th>
        <td><%= @matter.file_user&.name %></td>
      </tr>

      <tr>
        <th style="width:50%">文件变更时间</th>
        <td><%= simple_time_mini @matter.last_update_at %></td>
      </tr>

      <tr>
        <th>
          文件
        </th>
        <td>
          <% if @matter.file_path.present?%>
            <a href="javascript:void(0)" onclick="show_file(this)" class="btn show-file" data-url="<%= @matter.preview_url%>" data-file-name="<%= @matter.file_name %>">
              <i class="fa fa-eye"></i><%= show_file_name '文件',  @matter %>
            </a>
            <%= link_to @matter.download_url, class: 'btn' do  %>
              <i class="fa fa-download"></i>
            <% end %>
          <% else %>
            <%= @matter.file_name %>
          <% end %>
        </td>
      </tr>


      </tbody>
    </table>
  </div>

  <div class="table-responsive col-sm-6">
    <table class="table">
      <tbody>
      <tr>
        <th style="width:50%">状态</th>
        <td><%= @matter.get_status %></td>
      </tr>
      <tr>
        <th style="width:50%">会签发起人</th>
        <td><%= @matter.countersign_user&.name %></td>
      </tr>
      <tr>
        <th style="width:50%">会签发起时间</th>
        <td><%= simple_time_mini @matter.countersign_at %></td>
      </tr>
      <tr>
        <th>备注</th>
        <td><%= @matter.desc %></td>
      </tr>
      </tbody>
    </table>
  </div>

  </div>

app/views/matters/_form.html.erb
<div id="form">
  <div class="modal-header" style="padding:5px; padding-left: 15px;">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="file-modal-label"></h4>
  </div>
  <%= simple_form_for(@matter, html: {class: 'form-horizontal group_form', onkeydown: "if(event.keyCode==13)return false;"}, wrapper: :horizontal_form) do |f| %>
    <div class="modal-body" >
      <%= f.input :name %>
      <%= f.input :desc%>
    </div>
  <% end %>
  <div class="modal-footer">
    <%= button_tag '保存', class: 'btn btn-primary commit commit', data: { disable_with: '保存中' } %>
    <button type="button" class="btn btn-default" data-dismiss="modal">返回</button>
  </div>

  <script type="text/javascript">
      // function getData(){
      //     var array_data = $('.group_form').serializeArray();
      //     var data = {}
      //     for (var i=0;i<array_data.length;i++)
      //     {
      //         data[array_data[i].name]= array_data[i].value;
      //     }
      //     console.log(data);
      //     return data;
      // }
      $(function(){
          $('.commit').click(function(){
              showSpinner();
              $.ajax({
                  type: "POST",
                  url: $('.group_form').attr('action'),
                  data: $('.group_form').serialize(),
                  dataType: 'script',
                  async: false,
                  error: function(request) {
                      alert("Connection error");
                  },
                  success: function(data) {
                      //接收后台返回的结果
                  }
              });

          });
          $('.select2').select2();
          $('.datepicker').datepicker({
              autoclose: true,
              language: 'zh-cn'
          });
      });
  </script>
</div>

app/views/matters/_list.html.erb
<div class="row" id="matter-list">
  <div class="col-md-12">
    <div class="box">
      <%= form_tag matters_path, method: :get do%>
      <div class="box-header with-border">
        <h3 class="box-title">Bom单列表</h3>
        <% if can? :new, :matters %>
          <small><%= link_to '添加Bom单', new_matter_path , class: 'font-a label bg-green', 'data-toggle' => "modal", 'data-target' => "#global-modal" %></small>
        <% end %>
      </div>
      <div class="box-tools">
        <div class="input-group input-group-sm">
          <div class="pull-right">
            <div class="col-xs-12">
              <input type="text" name="table_search" class="form-control" placeholder="检索" value="<%= params[:table_search] %>">
            </div>
          </div>

          <div class="input-group-btn">
            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
          </div>
        </div>
      </div>


      <% end %>
      <!-- /.box-header -->
      <div class="box-body">
        <table class="table table-bordered">
          <tr>
            <th>名称</th>
            <th>创建人</th>
            <th>最后变更人</th>
            <th>状态</th>
            <th>文件</th>
            <th></th>
          </tr>
          <tr>
            <% if matters.present? %>
              <% matters.each do |matter| %>
              <tr>
                <td>
                  <% if can? :show, :matters %>
                  <%= link_to matter.name, matter_path(matter) %>
                  <% else %>
                    <%= matter.name %>
                  <% end %>
                </td>
                <td><%= matter.user&.name %></td>
                <td><%= matter.file_user&.name %></td>
                <td><%= matter.get_status %></td>
                <td>
                  <% if matter.file_path.present?%>
                    <a href="javascript:void(0)" onclick="show_file(this)" class="btn show-file" data-url="<%= matter.preview_url%>" data-file-name="<%= matter.file_name %>">
                      <i class="fa fa-eye"></i><%= show_file_name '文件',  matter %>
                    </a>
                    <%= link_to matter.download_url, class: 'btn' do  %>
                      <i class="fa fa-download"></i>
                    <% end %>
                  <% else %>
                    <%= matter.file_name %>
                  <% end %>
                </td>
                <td>

                  <% if can? :edit, :matters %>
                    <%= link_to  edit_matter_path(matter), class: 'btn btn-success btn-xs', 'data-toggle' => "modal", 'data-target' => "#global-modal" do %>
                      <i class="fa fa-edit"></i>编辑
                    <% end %>
                  <% end %>
                  <% if can? :destroy, :matters %>
                    <%= link_to matter_path(matter), method: :delete, data: {confirm: '确定删除吗？'}, class: 'btn btn-danger btn-xs' do %>
                                        <i class="fa fa-close"></i>删除
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="5" align="center">没有可显示的内容</td>
            </tr>
          <% end %>
          </tr>

        </table>
      </div>
      <!-- /.box-body -->
      <div class="box-footer clearfix">
        <div class="pull-right pagination-sm no-margin">
          <%= paginate matters, params: {table_search: params[:table_search]} %>
        </div>
      </div>
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/matters/agree.js.erb
$('#global-modal').modal('hide');
show_flash('success', '已会签')
location.reload();

app/views/matters/countersign.js.erb
show_flash('success', '已发起会签')
location.reload();

app/views/matters/create.js.erb
<% if @flag %>
$('#global-modal').modal('hide');
show_flash('success', '创建成功')
location.reload();
<% else %>
hideSpinner();
$('#form').html('<%= j render "/matters/form"%>');
<% end %>

app/views/matters/edit.html.erb
<%= render 'matters/form' %>

app/views/matters/index.html.erb
<%= render 'matters/header' %>

<%= render partial: 'matters/list', locals: {matters: @matters} %>

app/views/matters/new.html.erb
<%= render 'matters/form' %>

app/views/matters/send_notice.js.erb
$('#global-modal').modal('hide');
show_flash('success', '发送成功')
location.reload();

app/views/matters/show.html.erb
<%= render 'matters/header' %>
<div class="row">
  <div class="box-body">
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs" data-turbolinks="false">
        <li class="active"><a href="#tab_1" data-toggle="tab">基本信息</a></li>
        <li><a href="#tab_2" data-toggle="tab">文件历史</a></li>
        <% if @matter.status != 'circulation' %>
        <li><a href="#tab_3" data-toggle="tab">会签</a></li>
        <% end %>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="tab_1">
          <%= render 'matters/detail' %>
        </div>
        <div class="tab-pane" id="tab_2">
          <%= render 'matters/versions' %>
        </div>
        <% if @matter.status != 'circulation' %>
        <div class="tab-pane" id="tab_3">
          <%= render 'matters/countersign' %>
        </div>
        <% end %>
      </div>
      <!-- /.tab-content -->
      <div class="modal-footer">
        <%= link_to '上传bom单', upload_file_matter_path(@matter), 'data-toggle' => "modal", 'data-target' => "#global-modal", class: 'btn btn-success' if can? :upload_file, :matters %>
        <%= link_to '流转通知', notices_matter_path(@matter), 'data-toggle' => "modal", 'data-target' => "#global-modal", class: 'btn btn-primary'  if(can?(:notices, :matters) && @matter.status == 'circulation')%>

        <%= button_tag '发起会签', class: 'btn btn-danger commit', id: 'countersign' if(can?(:countersign, :matters) && @matter.status == 'circulation')%>
        <%= link_to '返回', matters_path, class: 'btn btn-default' %>
      </div>
    </div>
    <!-- nav-tabs-custom -->

  </div>

  <!-- 初始化按钮 start -->
  <div class="col-md-12">
  </div>
  <!-- 初始化按钮 end -->
  <!-- 初始化配置 start -->
  <script type="text/javascript">
      $(function(){
          $('#countersign').click(function(){
              if(confirm('确认发起会签吗？')){
                  showSpinner();
                  $.ajax({
                      type: "PATCH",
                      url: '<%= countersign_matter_path @matter %>',
                      dataType: 'script',
                      async: false,
                      error: function(request) {
                          alert("Connection error");
                      },
                      success: function(data) {
                          //接收后台返回的结果
                      }
                  });
              }
          });
      });
  </script>
</div>

app/views/matters/update.js.erb
<% if @flag %>
$('#global-modal').modal('hide');
show_flash('success', '修改成功')
location.reload();
<% else %>
hideSpinner();
$('#form').html('<%= j render "/matters/form"%>');
<% end %>

app/views/matters/upload_file.html.erb
<div id="form">
  <div class="modal-header" style="padding:5px; padding-left: 15px;">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="file-modal-label"></h4>
  </div>
  <%= simple_form_for(@matter, html: {class: 'form-horizontal group_form', onkeydown: "if(event.keyCode==13)return false;"}, wrapper: :horizontal_form) do |f| %>
    <div class="modal-body" >
      <div class="form-group row string optional matter_attachment">
        <label class="col-sm-3 col-form-label string optional" for="matter_attachment">文件</label>
        <div class="col-sm-9">
          <a class="btn btn-xs bg-blue" id="matter_attachment" href="#" >
            <i class="fa fa-plus"></i>
            <span>选择文件</span>
          </a>
          <span id="filename"></span>
        </div>
      </div>

    </div>
  <% end %>

  <div class="modal-footer">
    <%= button_tag '保存', class: 'btn btn-primary commit', data: { disable_with: '保存中' } %>
    <button type="button" class="btn btn-default" data-dismiss="modal">返回</button>
  </div>
</div>

<script type="text/javascript">
    function set_option(name){
        return {
            runtimes: 'html5,html4',          //上传模式,依次退化
            browse_button: name,       //上传选择的点选按钮，**必需**
            uptoken : '<%= @uptoken %>',
            //若未指定uptoken_url,则必须指定 uptoken ,uptoken由其他程序生成
            unique_names: false,
            // 默认 false，key为文件名。若开启该选项，SDK会为每个文件自动生成key（文件名）
            save_key: false,
            // 默认 false。若在服务端生成uptoken的上传策略中指定了 `sava_key`，则开启，SDK在前端将不对key进行任何处理
            domain: '<%= Rails.application.config.qiniu_domain %>',
            //bucket 域名，下载资源时用到，**必需**
            // container: 'container',           //上传区域DOM ID，默认是browser_button的父元素，
            max_file_size: '150mb',           //最大文件体积限制
            // flash_swf_url: 'js/plupload/Moxie.swf',  //引入flash,相对路径
            max_retries: 3,                   //上传失败最大重试次数
            // dragdrop: true,                   //开启可拖曳上传
            // drop_element: 'container',        //拖曳上传区域元素的ID，拖曳文件或文件夹后可触发上传
            chunk_size: '4mb',                //分块上传时，每片的体积
            auto_start: false,                 //选择文件后自动上传，若关闭需要自己绑定事件触发上传
            filters: [
                {title: "files", extensions: "xls,xslx,doc,docx,pdf,png,jpg,jpeg,gif,bmp,dwg,step,stl,stp"}
            ],
            init: {
                'FilesAdded': function (up, files) {
                    plupload.each(files, function (file) {
                        // 文件添加进队列后,处理相关的事情
                        $('#filename').text(file.name);
                    });
                },
                'BeforeUpload': function (up, file) {
                    showSpinner();
                    // 加载loading
                    // 每个文件上传前,处理相关的事情
                },
                'UploadProgress': function (up, file) {
                    // 每个文件上传时,处理相关的事情
                },
                'FileUploaded': function (up, file, info) {
                    // 每个文件上传成功后,处理相关的事情
                    // 其中 info 是文件上传成功后，服务端返回的json，形式如
                    // {
                    //    "hash": "Fh8xVqod2MQ1mocfI4S4KpRL6D98",
                    //    "key": "gogopher.jpg"
                    //  }
                    // 参考http://developer.qiniu.com/docs/v6/api/overview/up/response/simple-response.html
                    var domain = up.getOption('domain');
                    console.log(info);
                    var res = $.parseJSON(info.response);
                    // var res = parseJSON(info);
                    var sourceLink = domain + res.key; //
                    // 提交到服务器
                    // console.log(info);
                    $.ajax({
                        type: 'PATCH',
                        url: '<%= do_upload_file_matter_path @matter  %>',
                        data: {path: res.key, file_name: file.name},
                        dataType: 'script',
                        success: function (data) {

                        }
                    })
                },
                'Error': function (up, err, errTip) {
                    //上传出错时,处理相关的事情
                    console.log(err);
                    alert(err.message);
                },
                'UploadComplete': function () {
                    //队列文件处理完毕后,处理相关的事情
                    console.log('complete')
                },
                'Key': function (up, file) {
                    // 若想在前端对每个文件的key进行个性化处理，可以配置该函数
                    // 该配置必须要在 unique_names: false , save_key: false 时才生效
                    console.log(up);
                    console.log(file)
                    var key = '<%= SecureRandom.uuid %>' + '.' + file.name.split('.').pop();
                    // do something with key here
                    return key
                }
            }
        }
    }
    $(function(){
        var qiniu = new QiniuJsSDK();
        var option = set_option('matter_attachment');
        var uploader = qiniu.uploader(option);

        $('.commit').click(function(){
            uploader.start();
        });
        setTimeout(function(){ uploader.refresh(); }, 1000);
    });
</script>