config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'heyen' && password == 'zxy123456'
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  root 'home#index'

  resources :products do
    member do
      get :show_version
      get :upload_file
      patch :do_upload_file
      get :edit_file
      patch :update_file
      get :apply
      patch :do_apply
    end
    collection do
      post :do_develop_audit
      post :do_flow_audit
      post :do_active_audit
      post :do_failed_audit
      get :import
      post :do_import
    end
  end

  resources :instances do
    member do
      get :show_version
      get :upload_file
      patch :do_upload_file
      get :edit_file
      patch :update_file
      get :apply
      patch :do_apply
    end
    collection do
      post :do_develop_audit
      post :do_flow_audit
      post :do_active_audit
      post :do_failed_audit
      get :import
      post :do_import
    end
  end

  resources :audits do
    collection do
      get :products
      get :instances
      get :technologies
    end
  end
  resources :technologies do
    member do
      get :show_version
      get :upload_file
      patch :do_upload_file
      get :edit_file
      patch :update_file
      get :apply
      patch :do_apply
    end
    collection do
      post :do_develop_audit
      post :do_flow_audit
      post :do_active_audit
      post :do_failed_audit
    end
  end
  resources :notices do
    collection do
      get :receives
      get :sends
    end
    member do
      get :show_notice
      get :reply
      patch :do_reply
      patch :read
    end
  end
  resources :home, only: [:index] do
    collection do
      get :cytoscape
      get :files_search
      get :stl
    end
  end

  resources :matters do
    member do
      get :upload_file
      patch :do_upload_file
      get :notices
      patch :send_notice
      patch :countersign
      patch :agree
    end
  end
end

app/models/audit.rb
class Audit < ActiveRecord::Base
  belongs_to :user
  belongs_to :product_log, -> {where(model_type: 'ProductLog')}, foreign_key: :model_id
  belongs_to :instance_log, -> {where(model_type: 'InstanceLog')}, foreign_key: :model_id
  belongs_to :technology_log, -> {where(model_type: 'TechnologyLog')}, foreign_key: :model_id
end

app/controllers/audits_controller.rb
class AuditsController < ApplicationController

  def index

  end

  def products
    @apply_product_logs = current_user.develop_product_logs.where(status: 'apply').order('product_logs.updated_at desc')
    @develop_product_logs = current_user.flow_product_logs.where(status: 'develop').order('product_logs.updated_at desc')
    @flow_product_logs = current_user.active_product_logs.where(status: 'flow').order('product_logs.updated_at desc')
  end

  def instances
    @apply_instance_logs = current_user.develop_instance_logs.where(status: 'apply').order('instance_logs.updated_at desc')
    @develop_instance_logs = current_user.flow_instance_logs.where(status: 'develop').order('instance_logs.updated_at desc')
    @flow_instance_logs = current_user.active_instance_logs.where(status: 'flow').order('instance_logs.updated_at desc')
  end

  def technologies
    @apply_technology_logs = current_user.develop_technology_logs.where(status: 'apply').order('technology_logs.updated_at desc')
    @develop_technology_logs = current_user.flow_technology_logs.where(status: 'develop').order('technology_logs.updated_at desc')
    @flow_technology_logs = current_user.active_technology_logs.where(status: 'flow').order('technology_logs.updated_at desc')
  end

end

app/helpers/audits_helper.rb
module AuditsHelper
end

app/views/audits/_header.html.erb
<% content_for :content_header do %>
  <h1>
    审批流程
    <small><%= get_title params %></small>

  </h1>
  <ol class="breadcrumb">
    <li>
      <%=link_to audits_path do %>
        <i class="fa fa-dashboard"></i> 审批流程
      <% end %>
    </li>
    <li class="active"><%= get_title params %></li>
  </ol>
<% end %>

app/views/audits/index.html.erb
<%= render 'audits/header' %>
<div class="row">
  <div class="box-body">
    <div class="row">
      <!-- ./col -->
      <% if can? :products, :audits %>
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
              <h4>产品图纸审批</h4>

              <p style="height: 13px;"></p>
            </div>
            <div class="icon">
              <i class="fa fa-leaf"></i>
            </div>
            <%= link_to products_audits_path, class: 'small-box-footer' do %>
              详情 <i class="fa fa-arrow-circle-right"></i>
            <% end %>
          </div>
        </div>
      <% end %>

      <% if can? :instances, :audits %>
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-primary">
            <div class="inner">
              <h4>零件图纸审批</h4>

              <p style="height: 13px;"></p>
            </div>
            <div class="icon">
              <i class="fa fa-cogs"></i>
            </div>
            <%= link_to instances_audits_path, class: 'small-box-footer' do %>
              详情 <i class="fa fa-arrow-circle-right"></i>
            <% end %>
          </div>
        </div>
      <% end %>

      <% if can? :technologies, :audits %>
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-yellow">
            <div class="inner">
              <h4>工艺文件审批</h4>

              <p style="height: 13px;"></p>
            </div>
            <div class="icon">
              <i class="fa fa-file-text"></i>
            </div>
            <%= link_to technologies_audits_path, class: 'small-box-footer' do %>
              详情 <i class="fa fa-arrow-circle-right"></i>
            <% end %>
          </div>
        </div>
      <% end %>


    </div>


  </div>

  <!-- 初始化按钮 start -->
  <div class="col-md-12">

  </div>
  <!-- 初始化按钮 end -->

  <!-- 初始化配置 start -->


</div>

app/views/audits/instances.html.erb
<%= render 'audits/header' %>
<div class="row">
  <div class="box-body">
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs" data-turbolinks="false">
        <% if can? :do_develop_audit, :instances %>
        <li><a href="#tab_1" data-toggle="tab">研发审批</a></li>
          <% end %>
        <% if can? :do_flow_audit, :instances %>
        <li><a href="#tab_2" data-toggle="tab">流程化审批</a></li>
          <% end %>
        <% if can? :do_active_audit, :instances %>
        <li><a href="#tab_3" data-toggle="tab">最终审批</a></li>
          <% end %>
      </ul>
      <div class="tab-content">
        <% if can? :do_develop_audit, :instances %>
        <div class="tab-pane" id="tab_1">
          <%= render 'audits/instances/apply_instances' %>
        </div>
          <% end %>
        <% if can? :do_flow_audit, :instances %>
        <div class="tab-pane" id="tab_2">
          <%= render 'audits/instances/develop_instances' %>
        </div>
          <% end %>
        <!-- /.tab-pane -->
        <% if can? :do_active_audit, :instances %>
        <div class="tab-pane" id="tab_3">
          <%= render 'audits/instances/flow_instances' %>
        </div>
          <% end %>
        <!-- /.tab-pane -->
      </div>
      <!-- /.tab-content -->
      <div class="modal-footer">
        <%= link_to '返回', audits_path, class: 'btn btn-default' %>
      </div>
    </div>
    <!-- nav-tabs-custom -->

  </div>

  <!-- 初始化按钮 start -->
  <div class="col-md-12">
  </div>
  <!-- 初始化按钮 end -->
  <!-- 初始化配置 start -->
</div>
<script type="text/javascript">
  $(function(){
      $('.nav-tabs li a').first().click();
  })
  function failed(id){
      if(confirm('确认打回吗？')){
          showSpinner();
          $.ajax({
              type: 'post',
              url: '<%= do_failed_audit_instances_path %>',
              data: {id: id},
              dataType: 'script',
              success: function (data) {

              }
          })
      }

  }
</script>

app/views/audits/products.html.erb
<%= render 'audits/header' %>
<div class="row">
  <div class="box-body">
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs" data-turbolinks="false">
        <% if can? :do_develop_audit, :products %>
        <li><a href="#tab_1" data-toggle="tab">研发审批</a></li>
          <% end %>
        <% if can? :do_flow_audit, :products %>
        <li><a href="#tab_2" data-toggle="tab">流程化审批</a></li>
          <% end %>
        <% if can? :do_active_audit, :products %>
        <li><a href="#tab_3" data-toggle="tab">最终审批</a></li>
          <% end %>
      </ul>
      <div class="tab-content">
        <% if can? :do_develop_audit, :products %>
        <div class="tab-pane" id="tab_1">
          <%= render 'audits/products/apply_products' %>
        </div>
          <% end %>
        <% if can? :do_flow_audit, :products %>
        <div class="tab-pane" id="tab_2">
          <%= render 'audits/products/develop_products' %>
        </div>
          <% end %>
        <!-- /.tab-pane -->
        <% if can? :do_active_audit, :products %>
        <div class="tab-pane" id="tab_3">
          <%= render 'audits/products/flow_products' %>
        </div>
          <% end %>
        <!-- /.tab-pane -->
      </div>
      <!-- /.tab-content -->
      <div class="modal-footer">
        <%= link_to '返回', audits_path, class: 'btn btn-default' %>
      </div>
    </div>
    <!-- nav-tabs-custom -->

  </div>

  <!-- 初始化按钮 start -->
  <div class="col-md-12">
  </div>
  <!-- 初始化按钮 end -->
  <!-- 初始化配置 start -->
</div>
<script type="text/javascript">
  $(function(){
      $('.nav-tabs li a').first().click();
  })
  function failed(id){
      if(confirm('确认打回吗？')){
          showSpinner();
          $.ajax({
              type: 'post',
              url: '<%= do_failed_audit_products_path %>',
              data: {id: id},
              dataType: 'script',
              success: function (data) {

              }
          })
      }

  }
</script>

app/views/audits/technologies.html.erb
<%= render 'audits/header' %>
<div class="row">
  <div class="box-body">
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs" data-turbolinks="false">
        <% if can? :do_develop_audit, :technologies %>
        <li><a href="#tab_1" data-toggle="tab">研发审批</a></li>
          <% end %>
        <% if can? :do_flow_audit, :technologies %>
        <li><a href="#tab_2" data-toggle="tab">流程化审批</a></li>
          <% end %>
        <% if can? :do_active_audit, :technologies %>
        <li><a href="#tab_3" data-toggle="tab">最终审批</a></li>
          <% end %>
      </ul>
      <div class="tab-content">
        <% if can? :do_develop_audit, :technologies %>
        <div class="tab-pane" id="tab_1">
          <%= render 'audits/technologies/apply_technologies' %>
        </div>
          <% end %>
        <% if can? :do_flow_audit, :technologies %>
        <div class="tab-pane" id="tab_2">
          <%= render 'audits/technologies/develop_technologies' %>
        </div>
          <% end %>
        <!-- /.tab-pane -->
        <% if can? :do_active_audit, :technologies %>
        <div class="tab-pane" id="tab_3">
          <%= render 'audits/technologies/flow_technologies' %>
        </div>
          <% end %>
        <!-- /.tab-pane -->
      </div>
      <!-- /.tab-content -->
      <div class="modal-footer">
        <%= link_to '返回', audits_path, class: 'btn btn-default' %>
      </div>
    </div>
    <!-- nav-tabs-custom -->

  </div>

  <!-- 初始化按钮 start -->
  <div class="col-md-12">
  </div>
  <!-- 初始化按钮 end -->
  <!-- 初始化配置 start -->
</div>
<script type="text/javascript">
  $(function(){
      $('.nav-tabs li a').first().click();
  })
  function failed(id){
      if(confirm('确认打回吗？')){
          showSpinner();
          $.ajax({
              type: 'post',
              url: '<%= do_failed_audit_technologies_path %>',
              data: {id: id},
              dataType: 'script',
              success: function (data) {

              }
          })
      }

  }
</script>