config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'heyen' && password == 'zxy123456'
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  root 'home#index'

  resources :products do
    member do
      get :show_version
      get :upload_file
      patch :do_upload_file
      get :edit_file
      patch :update_file
      get :apply
      patch :do_apply
    end
    collection do
      post :do_develop_audit
      post :do_flow_audit
      post :do_active_audit
      post :do_failed_audit
      get :import
      post :do_import
    end
  end

  resources :instances do
    member do
      get :show_version
      get :upload_file
      patch :do_upload_file
      get :edit_file
      patch :update_file
      get :apply
      patch :do_apply
    end
    collection do
      post :do_develop_audit
      post :do_flow_audit
      post :do_active_audit
      post :do_failed_audit
      get :import
      post :do_import
    end
  end

  resources :audits do
    collection do
      get :products
      get :instances
      get :technologies
    end
  end
  resources :technologies do
    member do
      get :show_version
      get :upload_file
      patch :do_upload_file
      get :edit_file
      patch :update_file
      get :apply
      patch :do_apply
    end
    collection do
      post :do_develop_audit
      post :do_flow_audit
      post :do_active_audit
      post :do_failed_audit
    end
  end
  resources :notices do
    collection do
      get :receives
      get :sends
    end
    member do
      get :show_notice
      get :reply
      patch :do_reply
      patch :read
    end
  end
  resources :home, only: [:index] do
    collection do
      get :cytoscape
      get :files_search
      get :stl
    end
  end

  resources :matters do
    member do
      get :upload_file
      patch :do_upload_file
      get :notices
      patch :send_notice
      patch :countersign
      patch :agree
    end
  end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id           :integer          not null, primary key
#  category_id  :integer
#  name         :string(255)
#  product_no   :string(255)
#  color        :string(255)
#  norms        :string(255)
#  file_name    :string(255)
#  file_path    :string(255)
#  desc         :text(65535)
#  user_id      :integer
#  last_user_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Product < ActiveRecord::Base
  include FileConcern
  has_paper_trail versions: {
      scope: -> { order("id desc") }
  }
  has_many :notices, -> {where(model_type: 'Product')}, class_name: 'Notice', foreign_key: :model_id
  belongs_to :user
  belongs_to :last_user, foreign_key: :last_user_id, class_name: 'User'
  belongs_to :file_user, foreign_key: :file_user_id, class_name: 'User'
  has_many :product_logs
  has_many :products_instances
  belongs_to :technology
  validates_presence_of :name, :product_no
  has_and_belongs_to_many :instances, join_table: 'products_instances'
  has_and_belongs_to_many :organizations, join_table: 'product_organizations'
  has_and_belongs_to_many :users, join_table: 'products_users'
  validates_uniqueness_of :name, :product_no

  # after_save :do_stp2_stl


  def view_logs user
    if user.has_product_log_resource?
      self.product_logs
    else
      self.product_logs.where(user: user)
    end
  end

  def get_model_name
    '产品'
  end

  class << self
    def search_conn params
      products = Product.joins(:user).all
      if params[:table_search].present?
        products = products.where('products.product_no like ? or products.name like ? or products.norms like ? or users.name like ?',
                                  "%#{params[:table_search]}%", "%#{params[:table_search]}%", "%#{params[:table_search]}%",
                                  "%#{params[:table_search]}%")
      end
      products
    end

    def get_model_name
      '产品'
    end


    def format_files files, develop_id, flow_id, active_id, user
      logger = Logger.new 'log/zip_upload.log'
      logger.info "----start format  #{files}------"
      reg = /\((.+?)\)/
      files.each do |file_name|
        logger.info "----start upload #{file_name}------"
        file_path = File.join "public/unzip/", file_name
        key = "#{SecureRandom.uuid}.#{file_name.split('.').last}"
        res = QiniuUploader.upload 'longsheng_gm', file_path, key
        logger.info "---- upload code  #{res}------"
        logger.info "----end upload #{file_name}------"
        if res == 200
          #删除文件
          File.delete file_path
          m = file_name.match(reg)
          if m.present?
            no = m[1]
            product = Product.find_by product_no: no
            if product.present?
              ProductLog.create file_name: file_name,file_path: key, product: product, user: user, status: :apply, apply_at: DateTime.now, develop_id: develop_id, flow_id: flow_id, active_id: active_id
            else
              instance = Instance.find_by instance_no: no
              if instance.present?
                InstanceLog.create file_name: file_name,file_path: key, instance: instance, user: user, status: :apply, apply_at: DateTime.now, develop_id: develop_id, flow_id: flow_id, active_id: active_id
              end
            end
          end
        end
      end
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :show_version, :upload_file, :do_upload_file]
  before_action :set_uptoken, only: [:upload_file, :edit_file]
  before_action :set_log, only: [:edit_file, :update_file, :apply, :do_apply]
  before_action :set_audit_log, only: [:do_develop_audit, :do_flow_audit, :do_active_audit, :do_failed_audit]
  include ApplicationHelper
  def index
    @products = Product.search_conn(params).order('updated_at desc').page(params[:page]).per(Settings.per_page)
  end

  def new
    @product = Product.new
    render layout: false
  end

  def create
    @product = Product.new
    @product.user = current_user
    @flag = @product.update product_permit
  end

  def show

  end

  def edit
    render layout: false
  end

  def update
    @flag = @product.update product_permit
  end

  def destroy
    if @product.destroy
      redirect_to products_path, notice: '删除成功'
    else
      redirect_to products_path, alert: '删除失败'
    end
  end

  def upload_file
    render layout: false
  end

  def do_upload_file
    @log = ProductLog.new product: @product, file_path: params[:path], file_name: params[:file_name], user: current_user
    @log.save validate: false
    render js: 'location.reload()'
  end

  def import
    render layout: false
  end

  def do_import
    if params[:develop_id].present? && params[:flow_id].present? && params[:active_id].present? && params[:file].present?
      File.open("#{Rails.root}/public/zip/#{params[:file].original_filename}", "wb") do |file|
        file.write params[:file].read
      end
      ZipJob.perform_later params[:file].original_filename, params[:develop_id], params[:flow_id], params[:active_id], current_user
      redirect_to products_path, notice: '上传成功，数据正在处理中。。。'
    else
      redirect_to products_path, alert: '数据不完整'
    end
  end

  def show_version
    @version = @product.versions.find_by id: params[:version_id]
    render layout: false
  end

  def apply
    render layout: false
  end

  def do_apply
    @product = @log.product
    begin
      if @log.update log_permit
        @log.do_apply!
        @flag = true
      else
        @flag = false
      end
    rescue => e
      @flag = false
    end
  end

  def edit_file
    render layout: false
  end

  def update_file
    @product = @log.product
    @log.attributes = {file_path: params[:path], file_name: params[:file_name]}
    @flag = @log.save validate: false
  end

  def do_develop_audit
    begin
      from_status = @log.status
      @log.do_develop_audit!
      @log.audits.create from_status: from_status, to_status: @log.status, user: current_user
      @flag = true
    rescue => e
      @flag = false
    end
    render js: 'location.reload()'
  end

  def do_flow_audit
    begin
      from_status = @log.status
      @log.do_flow_audit!
      @log.audits.create from_status: from_status, to_status: @log.status, user: current_user
      @flag = true
    rescue => e
      @flag = false
    end
    render js: 'location.reload()'
  end

  def do_active_audit
    begin
      from_status = @log.status
      @log.do_active_audit!
      @log.audits.create from_status: from_status, to_status: @log.status, user: current_user
      @flag = true
    rescue => e
      @flag = false
    end
    render js: 'location.reload()'
  end

  def do_failed_audit
    begin
      from_status = @log.status
      @log.do_failed_audit!
      @log.audits.create from_status: from_status, to_status: @log.status, user: current_user
      @flag = true
    rescue => e
      @flag = false
    end
    render js: 'location.reload()'
  end


  private

  def product_permit
    params.require('product').permit(:category_id,:product_no, :name, :norms, :desc, :technology_id,instance_ids: [], user_ids: [], organization_ids: [])
  end

  def log_permit
    params.require('product_log').permit(:develop_id, :flow_id, :active_id)
  end

  def set_product
    @product = Product.find_by id: params[:id]
    redirect_to products_path, alert: '找不到数据' unless @product.present?
  end

  def set_log
    @log = current_user.product_logs.find_by id: params[:id]
    redirect_to products_path, alert: '找不到数据' unless @log.present?
  end

  def set_audit_log
    @log = ProductLog.find_by id: params[:id]
    redirect_to products_path, alert: '找不到数据' unless @log.present?
  end

  def set_uptoken
    @uptoken = uptoken
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_apply_form.html.erb
<div id="form">
  <div class="modal-header" style="padding:5px; padding-left: 15px;">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="file-modal-label"></h4>
  </div>
  <%= simple_form_for(@log, url: do_apply_product_path(@log), html: {class: 'form-horizontal group_form', onkeydown: "if(event.keyCode==13)return false;"}, wrapper: :horizontal_form) do |f| %>
    <div class="modal-body" >
      <%= f.input :develop_id, collection: current_user.audit_users(:develop, :products).all.collect{|user| [user.name, user.id]}, input_html: { class: 'select2', width: '100%', style: 'width: 100%'} %>
      <%= f.input :flow_id, collection: current_user.audit_users(:flow, :products).all.collect{|user| [user.name, user.id]} , input_html: { class: 'select2', width: '100%', style: 'width: 100%'}%>
      <%= f.input :active_id, collection: current_user.audit_users(:active, :products).all.collect{|user| [user.name, user.id]} , input_html: { class: 'select2', width: '100%', style: 'width: 100%'}%>
    </div>
  <% end %>

  <div class="modal-footer">
    <%= button_tag '保存', class: 'btn btn-primary commit commit', data: { disable_with: '保存中' } %>
    <button type="button" class="btn btn-default" data-dismiss="modal">返回</button>
  </div>
</div>
<script tye="text/javascript">
    //ajax提交表单
    $(function(){
        $('.commit').click(function(){
            showSpinner();
            $.ajax({
                type: "Patch",
                url: $('.group_form').attr('action'),
                data: $('.group_form').serialize(),
                dataType: 'script',
                async: false,
                error: function(request) {
                    alert("Connection error");
                },
                success: function(data) {
                    //接收后台返回的结果
                }
            });

        });
        $('.select2').select2();
    });
</script>

app/views/products/_detail.html.erb
<div class="row">
  <div class="table-responsive col-sm-6">
    <table class="table">
      <tbody>
      <tr>
        <th style="width:50%">产品编号</th>
        <td><%= @product.product_no %></td>
      </tr>
      <tr>
        <th>产品名</th>
        <td><%= @product.name %></td>
      </tr>
      <tr>
        <th>型号</th>
        <td><%= @product.norms %></td>
      </tr>
      <tr>
        <th>备注</th>
        <td><%= @product.desc %></td>
      </tr>
      <tr>
        <th>图纸可见人员</th>
        <td>
          <% @product.users.each do |user| %>
            <span class="label label-primary " style="padding-bottom: 2px;padding-top: 2px;"><%= user.name %></span>
          <% end %>

        </td>
      </tr>
      <tr>
        <th>
          图纸
        </th>
        <td>
          <% if @product.file_path.present? && current_user.can_view?(@product)%>
            <a href="javascript:void(0)" onclick="show_file(this)" class="btn show-file" data-url="<%= @product.preview_url%>" data-file-name="<%= @product.file_name %>">
              <i class="fa fa-eye"></i><%= show_file_name '文件',  @product %>
            </a>
            <%= link_to @product.download_url, class: 'btn' do  %>
              <i class="fa fa-download"></i>
            <% end %>
          <% else %>
            <%= @product.file_name %>
          <% end %>
        </td>
      </tr>

      </tbody>
    </table>
  </div>
  <div class="table-responsive col-sm-6">
    <table class="table">
      <tbody>
      <tr>
        <th>创建人</th>
        <td><%= @product&.user&.name %></td>
      </tr>
      <tr>
        <th>创建时间</th>
        <td><%= simple_time @product.created_at %></td>
      </tr>
      <tr>
        <th>图纸变更人</th>
        <td><%= @product&.file_user&.name %></td>
      </tr>
      <tr>
        <th>图纸变更时间</th>
        <td><%= simple_time @product.last_updated_at %></td>
      </tr>
      <tr>
        <th>图纸可见部门</th>
        <td>
          <% @product.organizations.each do |org| %>
            <span class="label label-primary " style="padding-bottom: 2px;padding-top: 2px;"><%= org.name %></span>
          <% end %>

        </td>
      </tr>
      <tr>
        <th>关联零件</th>
        <td>
          <% @product.instances.each do |instance| %>
            <span class="label label-primary " style="padding-bottom: 2px;padding-top: 2px;"><%= "#{instance.instance_no} / #{instance.name}" %></span>
          <% end %>
        </td>
      </tr>
      <%# if can? :cytoscape, :home %>
<!--        <tr>-->
<!--          <th>-->
<!--            关系图-->
<!--          </th>-->
<!--          <td>-->
            <%#= link_to cytoscape_home_index_path(product_id: @product.id),  class: 'btn btn-primary btn-xs', target: "view_window" do %>
<!--              <i class="fa fa-gg"></i>关系图-->
            <%# end %>
<!--          </td>-->
<!--        </tr>-->
      <%# end %>
      </tbody>
    </table>
  </div>
</div>

app/views/products/_list.html.erb
<div class="row" id="product-list">
  <div class="col-md-12">
    <div class="box">
      <%= form_tag products_path, method: :get do %>
        <div class="box-header with-border">
          <h3 class="box-title">产品列表</h3>
          <% if can? :new, :products %>
            <small><%= link_to '添加产品', new_product_path, class: 'font-a label bg-green', 'data-toggle' => "modal", 'data-target' => "#global-modal" %></small>
          <% end %>
          <% if can? :import, :products %>
            <small><%= link_to '批量文件上传审核', import_products_path, 'data-toggle' => "modal", 'data-target' => "#global-modal", class: 'font-a label bg-primary' %></small>
          <% end %>
        </div>
        <div class="box-tools">
          <div class="input-group input-group-sm">
            <div class="pull-right">
              <div class="col-xs-12">
                <input type="text" name="table_search" class="form-control" placeholder="检索" value="<%= params[:table_search] %>">
              </div>
            </div>

            <div class="input-group-btn">
              <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
            </div>
          </div>
        </div>


      <% end %>
      <div class="box-body">

      <table id="demo" class="table table-bordered"></table>
      </div>
      <script type="text/javascript">
          var treeTable = $('#demo').bootstrapTreeTable({
              expandAll : false,                // 是否全部展开
              expandFirst : false,
              toolbar: null,//顶部工具条
              columns: [{
                  title: '编号',
                  field: 'no',
                  width: '20%',
                  formatter: function (value, row, index) {
                      if(row.model_type === '零件'){
                          return "<a href='/instances/" + row.model_id +  "'> " + row.no + "</a>"
                      }else{
                          return "<a href='/products/" + row.model_id +  "'> " + row.no + "</a>"
                      }
                  }
              },{
                  title: '名称',
                  field: 'name',
                  width: '20%'
              },{
                  title: '类型',
                  field: 'model_type',
                  width: '10%'
              },{
                  title: '型号',
                  field: 'norms',
                  width: '20%'
              },{
                  title: '创建人',
                  field: 'user_name',
                  width: '10%'
              },{
                  title: '操作',
                  field: 'action',
                  width: '20%',
                  formatter: function(value,row, index) {
                      var actions = [];
                      if(row.model_type === '产品'){
                          <% if can? :edit, :products %>
                          actions.push('<a class="btn btn-success btn-xs" data-toggle="modal" data-target="#global-modal" href="/products/' + row.model_id + '/edit"> <i class="fa fa-edit"></i>编辑 </a>');
                          <% end %>
                          <% if can? :destroy, :products %>
                          actions.push('<a data-confirm="确定删除吗？" style="margin-left:5px;"  class="btn btn-danger btn-xs" rel="nofollow" data-method="delete" href="/products/' + row.model_id + '"> <i class="fa fa-close"></i>删除 </a>');
                          <% end %>
                      }
                      return actions.join('');
                  }
              }],
              data: JSON.parse('<%= raw products_tree products %>')
          });
          $('.treetable-bars').hide();
      </script>
      <!-- /.box-body -->
      <div class="box-footer clearfix">
        <div class="pull-right pagination-sm no-margin">
          <%= paginate products, params: {table_search: params[:table_search]} %>
        </div>
      </div>
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/products/_versions.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="box">

      <!-- /.box-header -->
      <div class="box-body">
        <table class="table table-bordered">
          <tr>
            <th>产品编号</th>
            <th>产品名</th>
            <th>型号</th>
            <th>被变更时间</th>
            <th>图纸创建人</th>
            <th>图纸</th>
          </tr>
          <tr>
            <% if @product.versions.present? %>
              <% @product.versions.each do |version| %>
              <% if version.reify.present? %>
                <tr>
                  <td>
                    <% if can? :show_version, :products %>
                    <%= link_to version.reify.product_no, show_version_product_path(version.reify, version_id: version.id), 'data-toggle' => "modal", 'data-target' => "#global-modal" %>
                      <%else %>
                    <%= version.reify.product_no %>
                    <% end %>
                  </td>
                  <td><%= version.reify.name %></td>
                  <td><%= version.reify.norms %></td>
                  <td><%= simple_time_mini version.created_at %></td>
                  <td><%= version.reify&.file_user&.name %></td>
                  <td>
                    <% if version.reify.file_path.present?  %>
                      <% if current_user.can_view?(@product) %>
                        <a href="javascript:void(0)" onclick="show_file(this)" class="btn show-file" data-url="<%= version.reify.preview_url%>" data-file-name="<%= version.reify.file_name %>">
                          <i class="fa fa-eye"></i><%= show_file_name '文件',  version.reify %>
                        </a>
                        <%= link_to version.reify.download_url, class: 'btn' do  %>
                          <i class="fa fa-download"></i>
                        <% end %>
                      <% else %>
                        <%= show_file_name '文件',  version.reify  %>
                      <% end %>
                    <% end %>

                  </td>
                </tr>
              <% end %>
            <% end %>
          <% else %>
            <tr>
              <td colspan="5" align="center">没有可显示的内容</td>
            </tr>
          <% end %>
          </tr>
        </table>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
</div>

app/views/products/create.js.erb
<% if @flag %>
  $('#global-modal').modal('hide');
show_flash('success', '创建成功')
  location.reload();
<% else %>
hideSpinner();
  $('#form').html('<%= j render "/products/form"%>');
<% end %>

app/views/products/do_apply.js.erb
<% if @flag %>
show_flash('success', '申请成功');
location.reload()
<% else %>
$('#form').replaceWith('<%= j render(partial: 'products/apply_form') %>');
<% end %>
hideSpinner();

app/views/products/edit.html.erb
<%= render 'products/form' %>

app/views/products/edit_file.html.erb
<div id="form">
  <div class="modal-header" style="padding:5px; padding-left: 15px;">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="file-modal-label"></h4>
  </div>
  <%= simple_form_for(@log, url: '',html: {class: 'form-horizontal group_form', onkeydown: "if(event.keyCode==13)return false;"}, wrapper: :horizontal_form) do |f| %>
    <div class="modal-body" >
      <div class="form-group row string optional product_attachment">
        <label class="col-sm-3 col-form-label string optional" for="productattachment">文件</label>
        <div class="col-sm-9">
          <a class="btn btn-xs bg-blue" id="product_attachment" href="#" >
            <i class="fa fa-plus"></i>
            <span>选择文件</span>
          </a>
          <span id="filename"></span>
        </div>
      </div>

    </div>
  <% end %>

  <div class="modal-footer">
    <%= button_tag '保存', class: 'btn btn-primary commit', data: { disable_with: '保存中' } %>
    <button type="button" class="btn btn-default" data-dismiss="modal">返回</button>
  </div>
</div>

<script type="text/javascript">
    function set_option(name){
        return {
            runtimes: 'html5,html4',          //上传模式,依次退化
            browse_button: name,       //上传选择的点选按钮，**必需**
            uptoken : '<%= @uptoken %>',
            //若未指定uptoken_url,则必须指定 uptoken ,uptoken由其他程序生成
            unique_names: false,
            // 默认 false，key为文件名。若开启该选项，SDK会为每个文件自动生成key（文件名）
            save_key: false,
            // 默认 false。若在服务端生成uptoken的上传策略中指定了 `sava_key`，则开启，SDK在前端将不对key进行任何处理
            domain: '<%= Rails.application.config.qiniu_domain %>',
            //bucket 域名，下载资源时用到，**必需**
            // container: 'container',           //上传区域DOM ID，默认是browser_button的父元素，
            max_file_size: '150mb',           //最大文件体积限制
            // flash_swf_url: 'js/plupload/Moxie.swf',  //引入flash,相对路径
            max_retries: 3,                   //上传失败最大重试次数
            // dragdrop: true,                   //开启可拖曳上传
            // drop_element: 'container',        //拖曳上传区域元素的ID，拖曳文件或文件夹后可触发上传
            chunk_size: '4mb',                //分块上传时，每片的体积
            auto_start: false,                 //选择文件后自动上传，若关闭需要自己绑定事件触发上传
            filters: [
                {title: "files", extensions: "xls,xslx,doc,docx,pdf,png,jpg,jpeg,gif,bmp,dwg,step,stp"}
            ],
            init: {
                'FilesAdded': function (up, files) {
                    plupload.each(files, function (file) {
                        // 文件添加进队列后,处理相关的事情
                        $('#filename').text(file.name);
                    });
                },
                'BeforeUpload': function (up, file) {
                    showSpinner();
                    // 加载loading
                    // 每个文件上传前,处理相关的事情
                },
                'UploadProgress': function (up, file) {
                    // 每个文件上传时,处理相关的事情
                },
                'FileUploaded': function (up, file, info) {
                    // 每个文件上传成功后,处理相关的事情
                    // 其中 info 是文件上传成功后，服务端返回的json，形式如
                    // {
                    //    "hash": "Fh8xVqod2MQ1mocfI4S4KpRL6D98",
                    //    "key": "gogopher.jpg"
                    //  }
                    // 参考http://developer.qiniu.com/docs/v6/api/overview/up/response/simple-response.html
                    var domain = up.getOption('domain');
                    console.log(info);
                    var res = $.parseJSON(info.response);
                    // var res = parseJSON(info);
                    var sourceLink = domain + res.key; //
                    // 提交到服务器
                    // console.log(info);
                    $.ajax({
                        type: 'PATCH',
                        url: '<%= update_file_product_path @log  %>',
                        data: {path: res.key, file_name: file.name},
                        dataType: 'script',
                        success: function (data) {

                        }
                    })
                },
                'Error': function (up, err, errTip) {
                    //上传出错时,处理相关的事情
                    console.log(err);
                    alert(err.message);
                },
                'UploadComplete': function () {
                    //队列文件处理完毕后,处理相关的事情
                    console.log('complete')
                },
                'Key': function (up, file) {
                    // 若想在前端对每个文件的key进行个性化处理，可以配置该函数
                    // 该配置必须要在 unique_names: false , save_key: false 时才生效
                    console.log(up);
                    console.log(file)
                    var key = '<%= SecureRandom.uuid %>-' + file.name
                    // do something with key here
                    return key
                }
            }
        }
    }
    $(function(){
        var qiniu = new QiniuJsSDK();
        var option = set_option('product_attachment');
        var uploader = qiniu.uploader(option);

        $('.commit').click(function(){
            uploader.start();
        });
        setTimeout(function(){ uploader.refresh(); }, 1000);
    });
</script>

app/views/products/show.html.erb
<%= render 'products/header' %>
<div class="row">
  <div class="box-body">
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs" data-turbolinks="false">
        <li class="active"><a href="#tab_1" data-toggle="tab">基本信息</a></li>
        <li><a href="#tab_2" data-toggle="tab">历史版本</a></li>
        <li><a href="#tab_3" data-toggle="tab">图纸历史</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="tab_1">
          <%= render 'products/detail' %>
        </div>
        <div class="tab-pane" id="tab_2">
          <%= render 'products/versions' %>
        </div>
        <!-- /.tab-pane -->
        <div class="tab-pane" id="tab_3">
          <%= render 'products/product_logs' %>
        </div>
        <!-- /.tab-pane -->
      </div>
      <!-- /.tab-content -->
      <div class="modal-footer">
        <%= link_to '图纸上传', upload_file_product_path(@product), 'data-toggle' => "modal", 'data-target' => "#global-modal", class: 'btn btn-success' if can? :upload_file, :products %>
        <%= link_to '返回', products_path, class: 'btn btn-default' %>
      </div>
    </div>
    <!-- nav-tabs-custom -->

  </div>

  <!-- 初始化按钮 start -->
  <div class="col-md-12">
  </div>
  <!-- 初始化按钮 end -->
  <!-- 初始化配置 start -->
</div>

app/views/products/show_version.html.erb
<div class="modal-header" style="padding:5px; padding-left: 15px;">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h4 class="modal-title" id="file-modal-label"></h4>
</div>

<div class="modal-body" >
  <table class="table">
    <tbody>
    <tr>
      <th style="width:50%">产品编号</th>
      <td><%= @version.reify&.product_no %></td>
    </tr>
    <tr>
      <th>产品名</th>
      <td><%= @version.reify&.name %></td>
    </tr>
    <tr>
      <th>型号</th>
      <td><%= @version.reify&.norms %></td>
    </tr>
    <tr>
      <th>创建人</th>
      <td><%= @version.reify&.user&.name %></td>
    </tr>
    <tr>
      <th>被变更时间</th>
      <td><%= simple_time @version.created_at %></td>
    </tr>
    <tr>
      <th>图纸变更人</th>
      <td><%= @version.reify&.file_user&.name %></td>
    </tr>
    <tr>
      <th>图纸生效时间</th>
      <td><%= simple_time @version.reify&.active_at %></td>
    </tr>
    <tr>
      <th>备注</th>
      <td><%= @version.reify&.desc %></td>
    </tr>
    </tbody>
  </table>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">返回</button>
</div>

app/views/products/update.js.erb
<% if @flag %>
$('#global-modal').modal('hide');
show_flash('success', '修改成功')
location.reload();
<% else %>
hideSpinner();
$('#form').html('<%= j render "/products/form"%>');
<% end %>

app/views/products/update_file.js.erb
<% if @flag %>
show_flash('success', '变更成功');
<% else %>
show_flash('failed', '变更失败，请稍后重试');
<% end %>
$('#product_logs').replaceWith('<%= j render(partial: 'products/product_logs') %>');
hideSpinner();
$('#global-modal').modal('hide');